package day42_Exceptions_Continue;

public class ThrowKeyword {
    public static void main(String[] args) throws InterruptedException {
        System.out.println("______________test 1___________________");
        System.out.println("Hello");
        Thread.sleep(3000);
        System.out.println("Cydeo");

        System.out.println("________Test 1 Completed");

        System.out.println("______________test 2___________________");

        System.out.println("Hello");
        Thread.sleep(3000);
        System.out.println("Batch EU08");

        System.out.println("________Test 2 Completed");





    }
}
